---
title: "Ch 12: Tidy Data"
output: html_notebook
---



## Introduction

```{r}
library(tidyverse)
```

## Tidy Data

**NOTES**

- Add [Tidy Data](http://www.jstatsoft.org/v59/i10/paper) to reading
- Use COW war dataset as an example of non-tidy data
- Also WDI data for non-tidy data
- Replication datatsets are often non-tidy. Why?
- See this post by [Jeff Leek](http://simplystatistics.org/2016/02/17/non-tidy-data/)

The Rules

1. Each **variable** has its own **column**
2. Each **observation** muust have its own **row**
3. Each **value** must have its own **cell**

or even

1. Put each **dataset** in a **tibble**
2. Put each **variable** in a **column**

These seem obvious at first, so we need to see examples of not-following tidy data and what happens.

Some nuances:

The definitions of **variable**, **observation**, and **value** are not always clear. And how you store and arrange the data can depend on how you aim to use it. Generally, aim for storing the data in a tidy format that ensures minimal errors. When you model it, you can transform the data later.
See non-tidy data.

It is easier to work with variables in columns because of `mutate` and `summary` functions.
It will also work better with `tidyverse` functions: e.g. using `group_by` to group and summarize, or `facet_*` and aesthetics in **ggplot2**.

The tidy data ideas are adapted from the [database normalization](https://en.wikipedia.org/wiki/Database_normalization), but simplified and adapted to the general uses of practicing data scientists.



### Exercises

**TODO**

## Spreading and Gathering

### Exercises

**TODO**


## Separating and Uniting


### Exercises

**TODO**

## Missing Values


### Exercises

**TODO**


## Case Study

### Exercises

**TODO** 


## Non-Tidy Data

- Corpus and text data is often stored in sparse Matrices https://cran.r-project.org/web/packages/tm/tm.pdf
- Graphical data has its own format: http://igraph.org/r/doc/
