```{r include=FALSE, cache=FALSE}
set.seed(1014)
options(digits = 3)

.nojekyll <- here::here("docs", ".nojekyll")
if (!file.exists(.nojekyll)) {
  close(open(file(.nojekyll, "w")))
}

knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  cache = TRUE,
  autodep = TRUE,
  # need to save cache
  cache.extra = knitr::rand_seed,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold"
)

options(dplyr.print_min = 6, dplyr.print_max = 6)

is_html <- knitr::opts_knit$get("rmarkdown.pandoc.to") == "html"

# keep track of the current state
STATE <- NULL

BeginQuestion <- function() {
  if (!is.null(STATE)) {
    message(glue::glue("Starting Question block when STATE = {STATE}"))
    stop()
  }
  STATE <<- "Question"
  if (is_html) {
    "<blockquote class='question'>"
  } else {
     # "\\begin{quotation}"
  }
}
EndQuestion <- function() {
  if (is.null(STATE) || !STATE %in% "Question") {
    message(glue::glue("Ending Question block when STATE = {STATE}"))
    stop()
  }
  STATE <<- NULL
  if (is_html) {
    "</blockquote>"
  } else {
    # "\\end{quotation}"
  }
}

BeginAnswer <- function() {
  if (!is.null(STATE)) {
    message(glue::glue("Starting Answer block when STATE = {STATE}"))
    stop()
  }
  STATE <<- "Answer"
  if (is_html) {
    "<div class='answer'>"
  } else {
    # "\\begin{answer}"
  }
}
EndAnswer <- function() {
  if (is.null(STATE) || !STATE %in% "Answer") {
    message(glue::glue("Ending Answer block when STATE = {STATE}"))
    stop()
  }
  STATE <<- NULL
  if (is_html) {
    "</div>"
  } else {
    # "\\end{answer}"
  }
}
```
# Introduction

## Acknowledgments {-}

All the credit should go to Garrett Grolemund and Hadley Wickham for writing the truly fantastic *R for Data Science* book,
without which these solutions would not exist---literally.

This book was written in the open, with some people contributed pull requests to fix problems.
Thank you to all who contributed via [GitHub](https://github.com/jrnold/r4ds-exercise-solutions/graphs/contributors).

```{r contributions,echo=FALSE,cache=FALSE,message=FALSE,results='asis'}
library("dplyr")
clean_author <- function(x) {
  if_else(stringr::str_detect(x, "@users\\.noreply\\.github\\.com"),
          stringr::str_replace(x, "(.*?)@users\\.noreply\\.github\\.com", 
                               "\\\\@\\1"),
          stringr::str_c("<", x, ">"))
}

excluded_authors <- c("jeffrey.arnold@gmail.com")
contribs <- git2r::contributions(by = "author") %>%
  filter(!author %in% excluded_authors) %>%
  mutate(author = clean_author(author)) %>%
  arrange(author) 

cat("Thanks go to all contributers in alphabetical order: ")
cat(paste0(contribs$author, collapse = ", "))
cat(".\n")
```

## Updates {-}

```{r updates,results='asis',echo=FALSE,cache.extras=tools::md5sum(here::here("NEWS.md"))}
readr::read_file(here::here("NEWS.md")) %>%
  stringr::str_replace_all(stringr::regex("^## (.*)$", multiline = TRUE), 
                           "### \\1 {-}") %>%
  cat()
```

<!-- match unopened div --><div>
```{r include=FALSE, cache=FALSE}
if (!is.null(STATE)) {
  message(glue::glue("Unclosed Question or Answer block. STATE = {}"))
  stop()
}
```
