# Many Models


## Introduction

```{r}
library(modelr)
library(tidyverse)
library(gapminder)
```

Functions

- `nest`
- `unnest`
- `glance`

## Gapminder

```{r}
gapminder %>% 
  ggplot(aes(year, lifeExp, group = country)) +
    geom_line(alpha = 1/3)
```

```{r}
nz <- filter(gapminder, country == "New Zealand")
nz %>% 
  ggplot(aes(year, lifeExp)) + 
  geom_line() + 
  ggtitle("Full data = ")

nz_mod <- lm(lifeExp ~ year, data = nz)
nz %>% 
  add_predictions(nz_mod) %>%
  ggplot(aes(year, pred)) + 
  geom_line() + 
  ggtitle("Linear trend + ")

nz %>% 
  add_residuals(nz_mod) %>% 
  ggplot(aes(year, resid)) + 
  geom_hline(yintercept = 0, colour = "white", size = 3) + 
  geom_line() + 
  ggtitle("Remaining pattern")
```

```{r}
by_country <- gapminder %>% 
  group_by(country, continent) %>% 
  nest()
```

```{r}
by_country$data[[1]]
```


```{r}
country_model <- function(df) {
  lm(lifeExp ~ year, data = df)
}
```
```{r}
models <- map(by_country$data, country_model)
by_country <- by_country %>% 
  mutate(model = map(data, country_model))
by_country
```

```{r}
by_country <- by_country %>% 
  mutate(
    resids = map2(data, model, add_residuals)
  )
by_country
```

