---
output: html_document
editor_options:
  chunk_output_type: console
---

# Workflow: scripts

## Running code

No exercises

## RStudio diagnostics

No exercises

## Practice

### Exercise <span class="exercise-number">6.3.1</span> {.unnumbered .exercise}

`r BeginQuestion()`
Go to the RStudio Tips twitter account, <https://twitter.com/rstudiotips> and find one tip that looks interesting. Practice using it!
`r EndQuestion()`

`r BeginAnswer()`

Here's the current timeline of \@rstudiotips.

<a class="twitter-timeline" href="https://twitter.com/rstudiotips?ref_src=twsrc%5Etfw">Tweets by rstudiotips</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

`r EndAnswer()`

### Exercise <span class="exercise-number">6.3.2</span> {.unnumbered .exercise}

`r BeginQuestion()`
What other common mistakes will RStudio diagnostics report?
Read <https://support.rstudio.com/hc/en-us/articles/205753617-Code-Diagnostics> to find out.
`r EndQuestion()`

`r BeginAnswer()`

You should read that page, but some other diagnostics for R code include:

1.  Check for Missing, unmatched, partially matched, and too many arguments to functions
1.  Warn if a variable is not defined
1.  Warn if a variable is defined but not used
1.  Style diagnostics to ensure the code conforms to the [tidyverse style guide](http://adv-r.had.co.nz/Style.html).

`r EndAnswer()`
